runtime: python39 # or another supported version
entrypoint: gunicorn -b :$PORT main:app
instance_class: F2
service: default
env_variables:
  GAE_ENV: 'standard'

handlers:

# Matches requests to /images/... to files in static/images/...
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto